### ISSUE TITLE
SSSOM guide for mapping between DwC and MIxS terms

### ISSUE THREAD

**Issue by raissameyer** [tdwg/gbwg#9]
Hi @cmungall,

I had a look at the Simple Standard for Sharing Ontology Mappings ([SSSOM](https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md#common-mapping-predicates)), which looks like a good option to perform semantically precise mapping of related DwC and MIxS terms (I've had an exemplary first go at this below). 

Would you think that SSSOM could be a suitable option for this? Or should I be looking at some other guides?

Best, 
Raïssa

| subject_id | subject_label | subject_category | predicate_id | object_id |  object_label | object_category | match_type | comment |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | 
| [dwc:country](http://rs.tdwg.org/dwc/terms/version/country-2017-10-06.htm) | Country | DwC Location | skos:closeMatch | MIXS:0000010 | geographic location (country and/or sea, region) | MIxS checklist | HumanCurated | DwC term expects the name of a country, while the MIxS term may either be the name of a country or a sea |
| [dwc:decimalLatitude](http://rs.tdwg.org/dwc/terms/version/decimalLatitude-2017-10-06.htm) | Decimal Latitude | DwC Location | skos:narrowMatch / ro:concretizes [RO:0000059] | MIXS:0000009 | geographic location (latitude and longitude) | MIxS checklist | HumanCurated | DwC term only covers part of the MIxS term (latitude) and specifies the writing convention |
| [dwc:decimalLongitude](http://rs.tdwg.org/dwc/terms/version/decimalLongitude-2017-10-06.htm) | Decimal Longitude | DwC Location | skos:narrowMatch / ro:concretizes [RO:0000059] | MIXS:0000009 | geographic location (latitude and longitude) | MIxS checklist | HumanCurated | DwC term only covers part of the MIxS term (longitude) and specifies the writing convention |

**Comment by 79-6d** [comment]
Hey @raissameyer 

I am so glad that this is being picked up! I am [posted a question about this in GGBN repo](https://github.com/tdwg/ggbn/issues/1) since July 2020, but it didn't seem to be picked up. So I appreciate that this is finally being mentioned! 

One of the Darwin Core extensions ([GGBN](https://terms.tdwg.org/wiki/GGBN_Data_Standard)) shows some of the similar types of mapping using Simple Knowledge Organization System ([SKOS](https://www.w3.org/TR/skos-reference/)) although it should be noted that SKOS is used to `link` concepts from different concept schemes. 

One of the examples:
[https://terms.tdwg.org/wiki/mixs:project_name](https://terms.tdwg.org/wiki/mixs:project_name)

project name  URI: [http://gensc.org/ns/mixs/project_name](http://gensc.org/ns/mixs/project_name)  
skos: has related match   [http://terms.tdwg.org/wiki/Dwc:datasetName](http://terms.tdwg.org/wiki/Dwc:datasetName)

My knowledge on ontology semantic is rather limited, but based on what I know, I think it could be a good idea to `identify` terms that can potentially be mapped using these systems as a guide.

**Comment by raissameyer** [comment]
Hi @79-6d, 

Much appreciate your input on this and thanks for sharing the example. 

> although it should be noted that SKOS is used to link concepts from different concept schemes. […] it could be a good idea to identify terms that can potentially be mapped using these systems as a guide 

Thanks for raising this. Reading more of the documentation of SKOS, especially the part on [Mapping](https://www.w3.org/TR/skos-reference/#mapping) and its subsection [10.6.8.](https://www.w3.org/TR/skos-reference/#L4858) on comparing SKOS and OWL terms, I’d agree that it might be worth thinking about using SKOS just to do an initial loose matching of terms of the two standards, but then explore other options for a final more powerful mapping where possible. 

@cmungall besides SKOS, SSSOM suggests using OWL or RDFS terms. Are there any additional sources for SSSOM mapping predicatives that we should be looking at?

**Comment by raissameyer** [comment]
For the DwC-MIxS mapping, we have now used the Simple Standard for Sharing Ontology Mappings, along with (following their guidance) SKOS predicates.
